Repository hgraph-io/hedera-walletconnect-utils, pull requests merged in 2023-11, with the labels that each got.

#46 Feature/include demo in lib
  build.mjs
  demo/build/build.mjs
  demo/src/dApp/main.ts
  demo/src/wallet/main.ts
  package-lock.json
  package.json
  src/lib/dapp/DAppSigner.ts
  src/lib/dapp/helpers.ts
  src/lib/dapp/index.ts
  src/lib/shared/utils.ts
  src/lib/wallet/index.ts
  src/lib/wallet/provider.ts
Labels: bug, devops

#65 don't remove dist folder when using npm run dev to avoid race conditions
  package.json
Labels: bug

#72 Error handling demo
  src/examples/typescript/dapp/index.html
  src/examples/typescript/dapp/main.ts
  src/examples/typescript/main.css
Labels: documentation, enhancement
